node1:
  image: marcelocenerine/jboss-clustering:latest
  ports:
    - 4447:4447
node2:
  image: marcelocenerine/jboss-clustering:latest
  ports:
    - 4547:4447
node3:
  image: marcelocenerine/jboss-clustering:latest
  ports:
    - 4647:4447
haproxy:
  image: marcelocenerine/haproxy:latest
  ports:
    - 80:80
    - 1936:1936
  links:
    - node1:node1
    - node2:node2
    - node3:node3

