node1:
  image: marcelocenerine/jboss-clustering:latest
node2:
  image: marcelocenerine/jboss-clustering:latest
httpd:
  image: marcelocenerine/httpd-modcluster:latest
  ports:
    - 80:80
    - 6666:6666